version: "3.8"

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    command: poetry run python src/manage.py runserver 0.0.0.0:8000
